### ISSUE TITLE
unable to use in webpack

### ISSUE THREAD

**Issue by bgrayburn** [ldthomas/apg-js2-lib#1]
I'm trying to use this library in the browser in a webpack application instead of a browserify application. Everytime it tries to build the bundle it complains about not being able to resolve the 'fs' module. Would you have any advice on solving this? I'll post any updates here for future users if I have any luck.

**Comment by ldthomas** [comment]
I have no experience with Webpack and for that matter very little experience with Browserify, except that using it to get my Node.js examples working in a browser was extremely easy. That said, `fs` is the file system module in Node.js and is `require()`-ed only in the `utilities.js exports.htmlToPage()` function. Writing to files from the utilities module was a bad idea and will be removed in the next version. It will just return the `html` and let the user decide where and how to display or save it. In the meantime I would suggest that you either modify or remove the `exports.htmlToPage` function in `utilities.js`.

**Comment by bgrayburn** [comment]
did it, thank you! It'll be much less Node specific when you do, which'll be great.

**Comment by bgrayburn** [comment]
just want to point out this also prevents using the trace functionality in the browser since it relies heavily on utilities. Would you be willing to review/accept pull requests that address this problem?

**Comment by ldthomas** [comment]
Have you tried the latest commit (f967025)? The utilities module has been heavily rewritten. There are no longer any references to "fs". htmlToPage() just returns a string. Also, the output of the trace facility has been heavily updated as well. Hopefully for the better.

**Comment by bgrayburn** [comment]
thank you! just tried it and love it. So nice to have full functionality in the browser!

**Comment by ldthomas** [comment]
In the latest commit I've add the files `apglib.js` and `apglib.css` which makes using `apg-lib` in a web page much easier. Check this [CodePen](http://codepen.io/apg-exp/pen/ZWKGqQ) for an example. I've used [RawGit](https://rawgit.com/) to serve the files from GitHub. OK to use those files if you want, but they are not guaranteed or reliable. Best to use your own server for production.
