### ISSUE TITLE
way to get trace as js obj

### ISSUE THREAD

**Issue by bgrayburn** [ldthomas/apg-js2-lib#2]
is there a way to get the information contained in the html trace output but as a js variable? I'd like to share with the user roughly where the parse is failing but haven't found access to this information yet.  Thank you again for this library, it's been a pleasure to use.

**Comment by ldthomas** [comment]
Not at this time. I'm working on a data visualization of the parse tree that will put out such an object, but that is a ways in the future. Your best bet is to add a function to trace.js with a loop something like:
````
var traceObj;
circular.forEach(function(lineIndex, index){
  var record = records[lineIndex];
  /* build traceObj to suit your needs */
});
````
Hope this helps.

**Comment by bgrayburn** [comment]
Would you be open to exposing the records object by adding it to the `this`
object? I can submit a pull request if you're open to this.

**Comment by ldthomas** [comment]
Not really. The records have a lot of data that refer to a lot of other internal data. Exposing it all would be a Pandora's Box. You can customize your own copy as you like, but I'd rather keep the records and all the data they contain under wraps. But thanks for your interest.

**Comment by bgrayburn** [comment]
I'm pretty surprised at this. Access to the parsed information in the
language that's doing the parsing seems expected. This will likely force me
to look elsewhere so I don't have to maintain my own parser repo. If you'd
prefer I make a stripped down js obj and expose that, would you consider a
pull request for that?

I've already exposed the records obj in a local copy for the time being and
had no problem interpreting that objecting and using it appropriately.

**Comment by ldthomas** [comment]
Sorry to make you look elsewhere, but it's just too much to expose. You would also have to make the circular buffer public (which does the job it needs to do but as a general object it's pretty anemic) and then assume that the user knew how to interpret the different opcode formats for each of the 18 different opcodes. The record formats are messy and were never intended to be public. Plus, you have to deal with incomplete sets if the max retained is exceeded. I'm not saying an experienced programmer and parsing expert can't handle this. They certainly can and I know some that have easily hacked up APG to their own liking. But I'm just not ready to expose all of that in general. 

As far as a js obj, as I said, I'm working on a version that will generate a trace object (in a JSON format). But I don't want to make any updates before that's ready to go.
